name: pashudhan_ai_frontend
description: "A Flutter-based frontend for the Pashudhan-AI application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2 # Added lottie package for animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/ # Added assets directory for the animation
